### ISSUE TITLE
Code enhacement

### ISSUE THREAD

**Issue by crsanti** [PedroJesusRomeroOrtega/colorPalette-Sass#1]
- I see you created palletes for dynamic properties. However this create multiple classname sentences (E.g.)

```css
/* Line13 */
.color_darknes_1 {
  border-color: #0000eb; }

/* Line 75 */
.color_darknes_1 {
  background-color: #eb00eb; }
```

I would like to see a `v2` using that mixin once and passing a map of properties with colors:

```sass
$properties: (
  "border-color": $borderColor,
  "background-color": $backgroundColor
);
@include colorPalette($properties, 21);
```

So inside you can apply for each className all properties. This would yield:

```css
.color_darknes_1 {
  border-color: #0000eb;
  background-color: #eb00eb; }

.color_darknes_2 {
  border-color: #0000d6;
  background-color: #d600d6; }

/* etc */
```

- It would be nice to add to ~~leeme.md~~ `README.md` a "how to use this repo to see your results" It would be:

### How to use
1. Clone this repo (You will need to have Node.js installed)
2. Open a command prompt inside project folder.
3. Execute `npm install` to install dependencies
4. Execute `npm run sass` to build CSS
5. Execute `npm start` to see the result (You can open [http://localhost:9005](http://localhost:9005] if your browser doesn't open automatically.

Overall you did a great job! :+1: Keep it up! :muscle:
